texts = [
    
    "Living men are bound by time... Thus, their lives have an urgency. This gives them ambition. Makes them choose those things that are most important, cling more tightly to that which they hold dear. Their lives have seasons, and rites of passage, and consequences. And ultimately, an end. But what of a life with no urgency? What then of ambition? What then of love?",
    "Usefulness, whatever form it may take, is the price we should pay for the air we breathe and the food we eat and the privilege of being alive.",
    "Success must include two things: the development of an individual to his utmost potentiality and a contribution of some kind to one's world.",
    "But the human tongue is a beast that few can master. It strains constantly to break out of its cage, and if it is not tamed, it will run wild and cause you grief. Power cannot accrue to those who squander their treasure of words.",
    "Allow me to tell you about some complex feelings. Feelings like the joy of finding another pasta lover. The admiration of another's puzzle-solving skills. The desire to have a cool, smart person to think you are cool. These feelings... They must be what you are feeling right now! I can hardly imagine what it must be like to feel that way.",
    "You cannot defeat me with a blade that does not sparkle with the power to repel evil! What you hold is useless. Go back to the world below, and tell that to the pathetic fools who made this blade! Its power is gone, and its edges are dull!",
    "Fine art is dead, Hobbes. Nobody understands it. Nobody likes it. Nobody sees it. It's irrelevant in today's culture. If you want to influence people, POPULAR art is the way to go. Mass market commercial art is the future. Besides, it's the only way to make serious money and that's what's important about being an artist.",
    "They say there are no stupid questions. That's obviously wrong; I think my question about hard and soft things, for example, is pretty stupid. But it turns out that trying to thoroughly answer a stupid question can take you to some pretty interesting places.",
    "Can't hold on much longer. but I will never let go! I know it's a one way track. Tell me now how long this'll last! I'm not gonna think this way. Not will I count on others! Close my eyes and feel it burn. Now I see what I gotta do! Open your heart, it's gonna be alright.",
    "It's freeing to know, it's all up to me, who I choose to be, what I choose to leave. This miracle that we get to witness, this pause in the chaos, it's Love. This speck in a galaxy, dot in a sunbeam, it's more than enough. You gotta realize your worth, you're meant to be on this earth. Think about how many miracles lead to your birth. Don't put a lock on your mind, life is yet to be defined. Beauty in the unknown, for a human this is home.",
    "Death doesn't exist. It never did, it never will. But we've drawn so many pictures of it, so many years, trying to pin it down, comprehend it, we've got to thinking of it as an entity, strangely alive and greedy. All it is, however, is a stopped watch, a loss, an end, a darkness. Nothing.",
    "We are like lambs in a field, disporting themselves under the eye of the butcher, who chooses out first one and then another for his prey. So it is that in our good days we are all unconscious of the evil Fate may have presently in store for us: sickness, poverty, mutilation, loss of sight or reason...",
    "And I may say, further, that a certain amount of care or pain or trouble is necessary for every man at all times. A ship without ballast is unstable and will not go straight."]
